version: '3'
services:
  bot:
    image: ghcr.io/sonozakisz/guild-mng-bot:latest
    volumes:
      - logs:/app/logs
      - storage:/app/storage
    # init: true  # docker stackでは使えないので不可
    # .envファイルではなく、環境変数を使用するが、docker-compose.ymlに直接書くのはよくないので、以下のようにする
    environment:
      TOKEN: ${TOKEN}
      APP_ID: ${APP_ID}
      GUILD_ID: ${GUILD_ID}
      LOCALE: ${LOCALE}
volumes:
  logs:
  storage:
